### ISSUE TITLE
...

### ISSUE THREAD

**Issue by cat-JS-0610-xyz** [kn0pkasanchouskoffeev/idle#1]
### Арбуз

**Comment by kn0pkasanchouskoffeev** [comment]
Спасибо, вкусно

**Comment by cat-JS-0610-xyz** [comment]
а сделай рол плэй

**Comment by kn0pkasanchouskoffeev** [comment]
> а сделай рол плэй

что за рол плэй?

**Comment by kn0pkasanchouskoffeev** [comment]
и вообще. ты мне меняешь статус и аватарку?

**Comment by cat-JS-0610-xyz** [comment]
всмысле

**Comment by cat-JS-0610-xyz** [comment]
рол плэй ну та ваша флудила в дс я еще тогда ливнул

**Comment by kn0pkasanchouskoffeev** [comment]
> рол плэй ну та ваша флудила в дс я еще тогда ливнул

а как это сделать здесь?

**Comment by kn0pkasanchouskoffeev** [comment]
Интересно было конечно. Но тут я такое сделать не смогу
