### ISSUE TITLE
> рол плэй ну та ваша флудила в дс я еще тогда ливнул

### ISSUE THREAD

**Issue by cat-JS-0610-xyz** [kn0pkasanchouskoffeev/idle#3]
> рол плэй ну та ваша флудила в дс я еще тогда ливнул

а как это сделать здесь?

_Originally posted by @kn0pkasanchouskoffeev in https://github.com/kn0pkasanchouskoffeev/idle/issues/1#issuecomment-778156143_

**Comment by cat-JS-0610-xyz** [comment]
Вспоминай

**Comment by kn0pkasanchouskoffeev** [comment]
> Вспоминай

чего блин

**Comment by cat-JS-0610-xyz** [comment]
у тебя был дс серв

**Comment by kn0pkasanchouskoffeev** [comment]
Ну был и был я не знаю как ты вообще представляешь это тут. Надо ведь чтобы ты и я учавствовали, но тут я вообще не понимаю как это можно реализовать.
